### PR TITLE
[WIP] 2.0.0

### PR DESCRIPTION
**Pull request by jpatel531**
- Support for multiple tab sharing. Any tab opened in the window of a sharing section will be synced across to the partner.
- Killing some views in favour of Atom's Notifications API
- Support for autocomplete/snippets
- Automatic copying of session ID to the clipboard

### CODE REVIEW

**Comment by jpatel531** [comment]
Should resolve #50 and #49

**Comment by rogerkk** [comment]
Wooho! \o/ Just thought I'd notify you of something, which I'm unsure if it's something you have control over or the error is somewhere else. Atom is now asking me to upgrade to v**3**.0.0:

selection_002

**Comment by jpatel531** [comment]
Yeah it's so annoying - basically there was something up with my git tags - I tried to abort but it was too late. I'm not sure if it's just cached by apm (because on github it's 2.0.0 and when i do `apm unpublish v3.0.0` it says package not found :/

**Comment by jpatel531** [comment]
oh wait... done

**Comment by jpatel531** [comment]
i forgot to do the `apm unpublish atom-pair@3.0.0`

**Comment by rogerkk** [comment]
I'm still seeing the same "Update to 3.0.0" message, even after restarting and checking for updates, as well as on the command line:

```
$ apm upgrade atom-pair
Package Updates Available (1)
└── atom-pair 1.1.6 -> 3.0.0

Would you like to install these updates? (yes) no
```

I guess this might be the caching you were referring to. :/

**Comment by rogerkk** [comment]
After yet another restart I was able to install the correct version. Can' t wait to test. :-)

**Pull request merged**
