### PR TITLE
Fix: Deprecated selector in `atom-pair/styles/atom_pair.less`

### PR DESCRIPTION
**Pull request by Grotax**
Fixes: #110 and #111

### CODE REVIEW

**Comment by davidgarland** [comment]
+1. Please push, author.

**Comment by gilfuser** [comment]
+2. Please push, author.

**Comment by ematta** [comment]
+3 Please push, author.

**Comment by 0x4156-AV** [comment]
+4 Please push, author.

**Comment by Talon24** [comment]
+5 Please push, author.

**Comment by agustif** [comment]
So I've just merged your PR into my own package because I hate deprecation calls, [atom-pair-less](https://atom.io/packages/atom-pair-less)

**Comment by mapio** [comment]
+6 please…

**Comment by agustif** [comment]
+7 please =)

**Comment by pauloprea** [comment]
+8

**Comment by m1guelpf** [comment]
@bookercodes @ewmy @gargath @hamchapman Updates?

**Comment by ewmy** [comment]
Thanks for this!

Sorry for the delay in approving.

**Comment by m1guelpf** [comment]
@ewmy Could you tag a new release?

**Comment by m1guelpf** [comment]
@bookercodes @ewmy @gargath @hamchapman Can you push a new release?

**Pull request merged**
